CREATE TABLE `{tabla}` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `amazon_order_id` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `merchant_order_id` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `purchase_date` DATETIME NULL DEFAULT NULL,
    `last_updated_date` DATETIME NULL DEFAULT NULL,
    `order_status` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `fulfillment_channel` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `sales_channel` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `order_channel` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `url` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `ship_service_level` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `product_name` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `sku` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `asin` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `number_of_items` INT NULL DEFAULT NULL,
    `item_status` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `tax_collection_model` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `tax_collection_responsible_party` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `quantity` INT NULL DEFAULT NULL,
    `currency` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `item_price` DECIMAL(10,2) NULL DEFAULT NULL,
    `item_tax` DECIMAL(10,2) NULL DEFAULT NULL,
    `shipping_price` DECIMAL(10,2) NULL DEFAULT NULL,
    `shipping_tax` DECIMAL(10,2) NULL DEFAULT NULL,
    `gift_wrap_price` DECIMAL(10,2) NULL DEFAULT NULL,
    `gift_wrap_tax` DECIMAL(10,2) NULL DEFAULT NULL,
    `item_promotion_discount` DECIMAL(10,2) NULL DEFAULT NULL,
    `ship_promotion_discount` DECIMAL(10,2) NULL DEFAULT NULL,
    `ship_city` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `ship_state` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `ship_postal_code` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `ship_country` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `promotion_ids` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `payment_method_details` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `item_extensions_data` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `is_business_order` TINYINT(1) NULL DEFAULT NULL,
    `purchase_order_number` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `price_designation` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `fulfilled_by` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `buyer_company_name` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `buyer_cst_number` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `buyer_vat_number` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `buyer_tax_registration_id` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `buyer_tax_registration_country` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `buyer_tax_registration_type` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `customized_url` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `customized_page` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `is_heavy_or_bulky` TINYINT(1) NULL DEFAULT NULL,
    `is_replacement_order` TINYINT(1) NULL DEFAULT NULL,
    `is_exchange_order` TINYINT(1) NULL DEFAULT NULL,
    `original_order_id` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `is_amazon_invoiced` TINYINT(1) NULL DEFAULT NULL,
    `vat_exclusive_item_price` DECIMAL(10,2) NULL DEFAULT NULL,
    `vat_exclusive_shipping_price` DECIMAL(10,2) NULL DEFAULT NULL,
    `vat_exclusive_giftwrap_price` DECIMAL(10,2) NULL DEFAULT NULL,
    `licensee_name` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `license_number` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `license_state` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `license_expiration_date` DATE NULL DEFAULT NULL,
    `is_iba` TINYINT(1) NULL DEFAULT NULL,
    `is_transparency` TINYINT(1) NULL DEFAULT NULL,
    `default_ship_from_address_name` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `default_ship_from_address_field_1` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `default_ship_from_address_field_2` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `default_ship_from_address_field_3` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `default_ship_from_city` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `default_ship_from_state` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `default_ship_from_country` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `default_ship_from_postal_code` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `is_ispu_order` TINYINT(1) NULL DEFAULT NULL,
    `store_chain_store_id` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `is_pickup_point_order` TINYINT(1) NULL DEFAULT NULL,
    `pickup_point_type` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `is_buyer_requested_cancellation` TINYINT(1) NULL DEFAULT NULL,
    `buyer_requested_cancel_reason` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `indice` VARCHAR(255) NOT NULL COLLATE 'latin1_swedish_ci',
    `indicemd5` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
    `fecha_add` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `fecha_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`) USING BTREE,
    INDEX `indice` (`indicemd5`) USING BTREE
) COLLATE='utf8mb4_0900_ai_ci' ENGINE=InnoDB;
